### ISSUE TITLE
TypeError: webfont is not a function

### ISSUE THREAD

**Issue by ptiry02** [itgalaxy/webfont#618]
I'm trying to use your library for my project, but when I try to execute the file I get the error saying webfont is not a function, can you help me?

```javascript
import webfont from 'webfont';

webfont({
  files: 'src/assets/icons/**/*.svg',
  fontName: 'my-icons',
  dest: 'src/assets/webfont-icons-test',
})
  .then((result) => {
    console.log('Result: ', result);
    return result;
  })
  .catch((error) => {
    console.log('There has been an error:\n', error);
  });
```
```zsh
> node devops/scripts/generate-icon-font.js

file:///[...]/devops/scripts/generate-icon-font.js:5
  webfont({
  ^

TypeError: webfont is not a function
    at file:///[...]/devops/scripts/generate-icon-font.js:5:3
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.1
```

**Comment by ptiry02** [comment]
nevermind, I fixed it! You should probably change the readme file to put:
```javascript
import { webfont } from 'webfont';
```
instead of: 
```javascript
import webfont from 'webfont';
```

**Comment by jimmyandrade** [comment]
Thanks @ptiry02 — glad you got it working.

## Cause

From **webfont 10+** the package uses **named exports** as the supported API (`import { webfont } from "webfont"`). A default import can fail under **ESM** (`"type": "module"` scripts) depending on how your bundler/Node resolves the package entry — you get an object instead of the function, hence `webfont is not a function`.

## Fix (12.1.0)

```javascript
import { webfont } from "webfont";

await webfont({
  files: "src/assets/icons/**/*.svg",
  fontName: "my-icons",
  dest: "src/assets/webfont-icons-test",
});
```

CommonJS:

```javascript
const { webfont } = require("webfont");
```

See [MIGRATION.md](https://github.com/itgalaxy/webfont/blob/master/MIGRATION.md) and the 12.0.0 breaking-change notes in [CHANGELOG.md](https://github.com/itgalaxy/webfont/blob/master/CHANGELOG.md).

We still ship `export default webfont` for compatibility, but **named import is recommended** and what we document going forward.

Closing — thanks for the README feedback; we will align remaining default-import examples in a follow-up docs PR.

**Comment by jimmyandrade** [comment]
Follow-up: PR #737 adds a `test:pack` guardrail (`scripts/pack-smoke-test.mjs`) that packs the current build with `npm pack`, installs the tarball into throwaway ESM and CJS consumer projects, and asserts every documented import shape — ESM default, ESM named, CJS default, CJS named — resolves to a callable function and can generate a real `woff2` from fixtures.

It runs on every PR (Node 24.x + 26.x matrix) and gates `npm publish` via `prepublishOnly`, so a broken `package.json#exports`, `files`, or `dist/*.mjs` cannot ship again.

I'll leave this issue open until the release that includes both the fix (#735) and the guardrail (#737) is published on npm. Once published, I'll comment here with the version and close.

**Comment by jimmyandrade** [comment]
Hi @ptiry02 — the fix is now **published on npm** in **webfont 12.1.1** (`latest`).

```shell
npm install webfont@latest
# or exactly: npm install webfont@12.1.1
```

## What shipped

- **#735** — webfont now ships a real ESM build (`dist/index.mjs`) and the `package.json#exports` field routes `import` → ESM and `require` → CJS. So `import webfont from "webfont"` returns the **callable function** instead of the module namespace object.
- **#737** — a three-layer publish guardrail (`publint` + `@arethetypeswrong/cli` + a pack-smoke test) now runs on every PR and gates `npm publish`, so this class of regression can't reach npm again.

## Both import styles work in 12.1.1

```js
// default import — was broken (TypeError: webfont is not a function), now works
import webfont from "webfont";
await webfont({ files: "icons/*.svg" });

// named import — the recommended form, still works
import { webfont } from "webfont";
await webfont({ files: "icons/*.svg" });

// CommonJS
const { webfont } = require("webfont");
```

## Could you test again?

If you still have the project where you hit this, please upgrade to `12.1.1` and confirm the **default import** now works for you.

Full details and a workaround for older versions are in the migration note: [`docs/migration/issue-0618-esm-default-import.md`](https://github.com/itgalaxy/webfont/blob/master/docs/migration/issue-0618-esm-default-import.md). Thanks again for the original report and the README feedback.
